import { Task } from "@/entities/task.entities";

export const TASKS: Task[] = [
  {
    id: 1,
    title: "API Integration Setup",
    subtitle: "Frontend Development",
    estimated: "6h estimated",
    progress: "TRACKING NOW",
    remaining: "High Priority",
    icon: { library: "Entypo", name: "code", size: 24, color: "white" },
    isActive: true,
    type: "analytics",
    percentage: "29%",
  },
  {
    id: 2,
    title: "Database Migration",
    subtitle: "QA",
    estimated: "2h estimated",
    progress: "TO DO",
    remaining: "High Priority",
    icon: { library: "MaterialIcons", name: "phone-iphone", size: 24, color: "white" },
    type: "analytics",
    percentage: "45%",
  },
  {
    id: 3,
    title: "Mobile UI Testing",
    subtitle: "QA",
    estimated: "4h estimated",
    progress: "TO DO",
    remaining: "High Priority",
    icon: { library: "MaterialIcons", name: "phone-iphone", size: 24, color: "white" },
    type: "mobile",
    percentage: "19%",
  },
  {
    id: 4,
    title: "Analytics Dashboard",
    subtitle: "Frontend",
    estimated: "6h estimated",
    progress: "TO DO",
    remaining: "Low Priority",
    icon: { library: "Octicons", name: "graph", size: 24, color: "white" },
    type: "analytics",
    percentage: "79%",
  },
  {
    id: 5,
    title: "User Authentication",
    subtitle: "Backend",
    estimated: "4h estimated",
    progress: "COMPLETED",
    remaining: "3.5h logged",
    icon: { library: "FontAwesome6", name: "users", size: 20, color: "white" },
    type: "auth",
    percentage: "9%",
  },
];
