import { TaskCardProps } from "@/entities/task.entities";

export const TASKS: TaskCardProps[] = [
  {
    id: 1,
    progress: "TRACKING NOW",
    remaining: "02:34:15",
    title: "API Integration Setup",
    subtitle: "Frontend Development",
    estimated: "6h estimated",
    icon: { library: "Entypo", name: "code", size: 24, color: "white" },
    isActive: true,
  },
  {
    id: 2,
    progress: "TO DO",
    remaining: "High Priority",
    title: "Database Migration",
    subtitle: "QA",
    estimated: "2h estimated",
    icon: { library: "MaterialIcons", name: "phone-iphone", size: 24, color: "white" },
  },
  {
    id: 3,
    progress: "TO DO",
    remaining: "High Priority",
    title: "Mobile UI Testing",
    subtitle: "QA",
    estimated: "2h estimated",
    icon: { library: "MaterialIcons", name: "phone-iphone", size: 24, color: "white" },
  },
  {
    id: 4,
    progress: "TO DO",
    remaining: "Low Priority",
    title: "Analytics Dashboard",
    subtitle: "Frontend",
    estimated: "6h estimated",
    icon: { library: "Octicons", name: "graph", size: 24, color: "white" },
  },
  {
    id: 5,
    progress: "COMPLETED",
    remaining: "3.5h logged",
    title: "User Authentication",
    subtitle: "Backend",
    estimated: "4h estimated",
    icon: { library: "FontAwesome6", name: "users", size: 20, color: "white" },
  },
  {
    id: 6,
    progress: "COMPLETED",
    remaining: "1h logged",
    title: "User Authentication",
    subtitle: "Backend",
    estimated: "1.5h estimated",
    icon: { library: "FontAwesome6", name: "users", size: 20, color: "white" },
  },
];
